/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exercicio;

import Control.Semaforo;
import java.awt.Color;

/**
 *
 * @author Ana Paula Fidelis e Bárbara Marquez
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public Tela() {
        initComponents();
        pnDonaJoana.setBackground(Color.GREEN);
        pnCliente1.setBackground(Color.GREEN);
        pnCliente2.setBackground(Color.GREEN);
        pnCliente3.setBackground(Color.GREEN);
        pnCliente4.setBackground(Color.GREEN);
        pnCliente5.setBackground(Color.GREEN);
        pnCliente6.setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        pnCliente2 = new javax.swing.JPanel();
        pnCliente1 = new javax.swing.JPanel();
        pnDonaJoana = new javax.swing.JPanel();
        pnCliente3 = new javax.swing.JPanel();
        pnCliente4 = new javax.swing.JPanel();
        pnCliente5 = new javax.swing.JPanel();
        pnCliente6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txLista = new javax.swing.JTextArea();
        btIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dona Joana");

        pnCliente2.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnCliente2Layout = new javax.swing.GroupLayout(pnCliente2);
        pnCliente2.setLayout(pnCliente2Layout);
        pnCliente2Layout.setHorizontalGroup(
            pnCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnCliente2Layout.setVerticalGroup(
            pnCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnCliente1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnCliente1Layout = new javax.swing.GroupLayout(pnCliente1);
        pnCliente1.setLayout(pnCliente1Layout);
        pnCliente1Layout.setHorizontalGroup(
            pnCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnCliente1Layout.setVerticalGroup(
            pnCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnDonaJoana.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnDonaJoanaLayout = new javax.swing.GroupLayout(pnDonaJoana);
        pnDonaJoana.setLayout(pnDonaJoanaLayout);
        pnDonaJoanaLayout.setHorizontalGroup(
            pnDonaJoanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnDonaJoanaLayout.setVerticalGroup(
            pnDonaJoanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnCliente3.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnCliente3Layout = new javax.swing.GroupLayout(pnCliente3);
        pnCliente3.setLayout(pnCliente3Layout);
        pnCliente3Layout.setHorizontalGroup(
            pnCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnCliente3Layout.setVerticalGroup(
            pnCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnCliente4.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnCliente4Layout = new javax.swing.GroupLayout(pnCliente4);
        pnCliente4.setLayout(pnCliente4Layout);
        pnCliente4Layout.setHorizontalGroup(
            pnCliente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnCliente4Layout.setVerticalGroup(
            pnCliente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnCliente5.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnCliente5Layout = new javax.swing.GroupLayout(pnCliente5);
        pnCliente5.setLayout(pnCliente5Layout);
        pnCliente5Layout.setHorizontalGroup(
            pnCliente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnCliente5Layout.setVerticalGroup(
            pnCliente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnCliente6.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnCliente6Layout = new javax.swing.GroupLayout(pnCliente6);
        pnCliente6.setLayout(pnCliente6Layout);
        pnCliente6Layout.setHorizontalGroup(
            pnCliente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        pnCliente6Layout.setVerticalGroup(
            pnCliente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel2.setText("Clientes");

        jLabel3.setText("Clientes que sairam");

        txLista.setColumns(20);
        jScrollPane1.setViewportView(txLista);

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnDonaJoana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btIniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel1)
                            .addGap(7, 7, 7))
                        .addComponent(pnDonaJoana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btIniciar))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        Cadeira cadeira = new Cadeira(this);

        Semaforo cheio = new Semaforo(6);
        Semaforo vazio = new Semaforo(0);
        Semaforo cheio2 = new Semaforo(1);
        Semaforo vazio2 = new Semaforo(0);

        Cliente c1 = new Cliente(1, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c2 = new Cliente(2, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c3 = new Cliente(3, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c4 = new Cliente(4, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c5 = new Cliente(5, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c6 = new Cliente(6, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c7 = new Cliente(7, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
        Cliente c8 = new Cliente(8, cadeira, cheio, vazio,cheio2,vazio2, 3, this);
      

        Atendente primeiroConsumidor = new Atendente(cheio2, vazio2, this);

        c1.start();
        c2.start();
        c3.start();
        c4.start();
        c5.start();
        c6.start();
        c7.start();
        c8.start();
        
        primeiroConsumidor.start();
    }//GEN-LAST:event_btIniciarActionPerformed

    
    public void addTextoTxLista(String texto){
        txLista.append("\n"+texto);
    }
    
    public void addCorClienteCadeira(int cadeira, Color cor){
        switch(cadeira){
                case 1: 
                    pnCliente1.setBackground(cor);
                    break;
                case 2: 
                    pnCliente2.setBackground(cor);
                    break;
                case 3: 
                    pnCliente3.setBackground(cor);
                    break;
                case 4: 
                    pnCliente4.setBackground(cor);
                    break;
                case 5: 
                    pnCliente5.setBackground(cor);
                    break;
                case 6: 
                    pnCliente6.setBackground(cor);
                    break;
                case 0: 
                    pnDonaJoana.setBackground(cor);
                    break;
            }                 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnCliente1;
    private javax.swing.JPanel pnCliente2;
    private javax.swing.JPanel pnCliente3;
    private javax.swing.JPanel pnCliente4;
    private javax.swing.JPanel pnCliente5;
    private javax.swing.JPanel pnCliente6;
    private javax.swing.JPanel pnDonaJoana;
    private javax.swing.JTextArea txLista;
    // End of variables declaration//GEN-END:variables
}
